services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
        test: curl --fail http://elasticsearch:9200/_health_report || exit 1
        interval: 30s
        timeout: 10s
        retries: 10
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  backend:
    image: full-text-search-backend
    build: ./backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - ELASTIC_ADDRESS=http://elasticsearch:9200
      - ALLOWED_HOSTS_URLS=http://localhost
  frontend:
    image: full-text-search-frontend
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080
    ports:
      - 80:80
    depends_on:
      - backend